"""Module for enums"""
from enum import Enum

class AssetType(Enum):
    """List of asset type"""
    CURRENCY  = "CURRENCY"
    COMMODITY = "COMMODITY"
    INDEX     = "INDEX"
    BOND      = "BOND"
    STOCK     = "STOCK"

class AssetEnum(Enum):
    """Parent of asset enum type"""

class Currency(AssetEnum):
    """List of currency"""
    AUD = "AUD"
    CAD = "CAD"
    CHF = "CHF"
    CNH = "CNH"
    CZK = "CZK"
    DKK = "DKK"
    EUR = "EUR"
    GBP = "GBP"
    HKD = "HKD"
    HUF = "HUF"
    JPY = "JPY"
    MXN = "MXN"
    NOK = "NOK"
    NZD = "NZD"
    PLN = "PLN"
    SEK = "SEK"
    SGD = "SGD"
    THB = "THB"
    TRY = "TRY"
    USD = "USD"
    ZAR = "ZAR"

class Commodity(AssetEnum):
    """List of commodity"""
    BTC = "BTC"
    BCH = "BCH"
    BCO = "BCO"
    XCU = "XCU"
    CORN = "CORN"
    ETH = "ETH"
    XAU = "XAU"
    LTC = "LTC"
    MBTC = "MBTC"
    NATGAS = "NATGAS"
    XPD = "XPD"
    XPT = "XPT"
    XAG = "XAG"
    SOYBN = "SOYBN"
    SUGAR = "SUGAR"
    WTICO = "WTICO"
    WHEAT = "WHEAT"

class Index(AssetEnum):
    """List of Index"""
    AU200 = "AU200"
    CH20 = "CH20"
    CHINAH = "CHINAH"
    CN50 = "CN50"
    DE10YB = "DE10YB"
    DE30 = "DE30"
    ESPIX = "ESPIX"
    EU50 = "EU50"
    FR40 = "FR40"
    HK33 = "HK33"
    JP225 = "JP225"
    JP225Y = "JP225Y"
    NAS100 = "NAS100"
    NL25 = "NL25"
    SG30 = "SG30"
    SPX500 = "SPX500"
    UK100 = "UK100"
    UK10YB = "UK10YB"
    US2000 = "US2000"
    US30 = "US30"
    USB02Y = "USB02Y"
    USB05Y = "USB05Y"
    USB10Y = "USB10Y"
    USB30Y = "USB30Y"

class Stock(AssetEnum):
    """List of Stock"""
    AAPL = "AAPL"
    GOOG = "GOOG"
